using System;
using System.Collections.Generic;

namespace Alphacert.Acc.Ods.Entities.Entities
{
    public partial class TransactionLegHistory
    {
        public int TransactionLegHistoryId { get; set; }
        public int TransactionHistoryId { get; set; }
        public DateTime FileDate { get; set; }
        public DateTime FileRunDateTime { get; set; }
        public string PortfolioCurrencyCode { get; set; }
        public string TransactionTypeCode { get; set; }
        public string TransactionSubTypeCode { get; set; }
        public long? JpmtransactionId { get; set; }
        public string HiportTransactionTypeCode { get; set; }
        public string HiportTransactionSubTypeCode { get; set; }
        public DateTime? TradeDate { get; set; }
        public DateTime? AccountingDate { get; set; }
        public DateTime? SettlementDate { get; set; }
        public DateTime? ActualSettlementDate { get; set; }
        public DateTime? EntryDateTime { get; set; }
        public string IsReversalFlag { get; set; }
        public decimal? Units { get; set; }
        public decimal? CostLocal { get; set; }
        public decimal? PriceLocal { get; set; }
        public decimal? ProceedsLocal { get; set; }
        public decimal? BrokerageExpense { get; set; }
        public decimal? StampDutyExpense { get; set; }
        public decimal? Gstexpense { get; set; }
        public decimal? Gstreclaim { get; set; }
        public decimal? IncomeLocal { get; set; }
        public string SettlementCurrencyCode { get; set; }
        public decimal? SettlementAmount { get; set; }
        public decimal? DividendInterestRate { get; set; }
        public string ExternalReferenceCode { get; set; }
        public decimal? ExchangeRateLocalToPortfolio { get; set; }
        public string ExchLclToPfMorDflag { get; set; }
        public decimal? TradeAmountBase { get; set; }
        public decimal? CostAmountBase { get; set; }
        public decimal? ProceedsBase { get; set; }
        public decimal? ExchangeRatePortfolioToUsd { get; set; }
        public string ExchPfToUsdmorDflag { get; set; }
        public string BrokerId { get; set; }
        public string BrokerName { get; set; }
        public int? LoadId { get; set; }
        public int? StagingRowId { get; set; }
        public bool? Inactive { get; set; }
        public string NttransactionId { get; set; }
        public decimal? AccruedInterestBase { get; set; }
        public decimal? BrokerCommBase { get; set; }
        public string NtassetCategoryCode { get; set; }
        public string NtassetCategorySubCode { get; set; }
        public string NtassetId1 { get; set; }
        public string NtassetId2 { get; set; }
        public string NtassetId2type { get; set; }
        public string NtassetSubCategoryName { get; set; }
        public string NtassetSuperCategoryName { get; set; }
        public string NtassetTicker1 { get; set; }
        public string NtassetTicker2 { get; set; }
        public string NtdataSource { get; set; }
        public string NtdepartmentCode { get; set; }
        public string NtdepotCode { get; set; }
        public string NteconomicSectorCode { get; set; }
        public DateTime? NtfileFromDate { get; set; }
        public string NtfileType { get; set; }
        public string NtindustryName { get; set; }
        public string NtindustrySectorName { get; set; }
        public string NtinternalReference { get; set; }
        public string NtoriginalTransactionId { get; set; }
        public string NtrecordDate { get; set; }
        public DateTime? NtrecordFrom { get; set; }
        public DateTime? NtrecordUpdated { get; set; }
        public string NtreportType { get; set; }
        public DateTime? NtrunDate { get; set; }
        public DateTime? NtrunTime { get; set; }
        public string NtsectorCode { get; set; }
        public string NtsubCategoryCode { get; set; }
        public string NtsuperCategoryCode { get; set; }
        public string NttaxCode { get; set; }
        public string NttransactionCategoryCode1 { get; set; }
        public string NttransactionCategoryCode2 { get; set; }
        public string NttransactionCodeGroup { get; set; }
        public string NttransactionStatus { get; set; }
        public decimal? OtherChargeBase { get; set; }
        public decimal? OtherTradeCharges { get; set; }
        public string PrincipalIncomeSplit { get; set; }
        public string ClearingBrokerId { get; set; }
        public string ClearingBrokerName { get; set; }
        public decimal? RealisedGainLossBase { get; set; }
        public decimal? RealisedGainLossLocal { get; set; }
        public string TransactionDescription { get; set; }
        public string CreditRatingMoodys { get; set; }
        public decimal? ExchangeGainLoass { get; set; }
        public string CreditRatingSandP { get; set; }
        public decimal? GrossAmountBase { get; set; }
        public decimal? GrossAmountLocal { get; set; }
        public int? BatchId { get; set; }
        public long? RelatedSecurityId { get; set; }
        public string RelatedSecuritySedol { get; set; }
        public decimal? BuyBaseAmount { get; set; }
        public decimal? ExchangeRateSpot { get; set; }
        public string ForwardCurrencyCode { get; set; }
        public decimal? ExchangeRateForward { get; set; }
        public decimal? ForwardPoints { get; set; }
        public decimal? ProfitOrLossBase { get; set; }
        public int? InstrumentId { get; set; }

        public TransactionHistory TransactionHistory { get; set; }
    }
}
